YAF-5286 adapt common-chart for better suport for secrets,
yiluhub/common-chart pull request #57
Opened 2024-07-23 14:38 UTC by guneriu

* list of static secrets can be passed
* introduced environmentSecrets parameter
* updated README.md for upgrade and new parameters
* updated chart release action to accept release-notes

# Pull Request

> Tracked in JIRA by [YAF-5286](https://yiluts.atlassian.net/browse/YAF-5286)

## Scope of the PR

Describe the scope of this pull request.

## Considerations / Implementation Details

Describe any considerations or implementation details.

2024-07-23 14:44 UTC, guneriu commented on yilu-common/values-test.yaml
> +secrets:
these resulted with 

```
# Source: yilu-common/templates/vaultSecret.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: booking-secrets
  labels:
    simpletrip: demo-service
spec:
  namespace: admin/yiluhub/
  vaultAuthRef: vault-secrets-operator/default
  mount: kv/services/secrets
  type: kv-v2
  path: bookings
  version: 1
  refreshAfter: 1h
  destination:
    name: booking-secrets
    create: true
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: payment-secrets
  labels:
    simpletrip: demo-service
spec:
  namespace: admin/yiluhub/
  vaultAuthRef: vault-secrets-operator/default
  mount: kv/services/secrets
  type: kv-v2
  path: payments
  version: 1
  refreshAfter: 1h
  destination:
    name: payment-secrets
    create: true
 ```

2024-07-23 14:45 UTC, guneriu commented on yilu-common/values-test.yaml
> +environmentSecrets:
and this
```
 env:
        - name: SPRING_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: spring-boot-cloud
              key: spring.environment
        - name: CLOUD_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: spring-boot-cloud
              key: cloud.environment
        - name: SERVER_PORT
          value: "8080"## helm range changes scope.
        - name: AUTHORIZATION_TOKEN
          valueFrom:
            secretKeyRef:
              name: booking-secrets
              key: AUTHORIZATION_TOKEN
        - name: WORLDSHOP_PRICING_API
          valueFrom:
            secretKeyRef:
              name: booking-secrets
              key: WORLDSHOP_PRICING_API## helm range changes scope.
        - name: username
          valueFrom:
            secretKeyRef:
              name: payment-secrets
              key: username
        - name: password
          valueFrom:
            secretKeyRef:
              name: payment-secrets
              key: password
      
              ```

2024-07-23 14:47 UTC, davidmukiibi-yilu requested changes

2024-07-23 14:47 UTC, davidmukiibi-yilu commented on yilu-common/README.md
> +You can fetch secrets from Vault via Vault Secrets Operator(VOS).
Vault Secrets Operator(VOS) should be Vault Secrets Operator(VSO)

2024-07-23 14:48 UTC, davidmukiibi-yilu commented on yilu-common/README.md
> +You can fetch secrets from Vault via Vault Secrets Operator(VOS).
only change is VSO

2024-07-23 14:49 UTC, davidmukiibi-yilu commented on yilu-common/values-test.yaml
> +secrets:
I see a problem here @guneriu , the 2 secrets are not separated by the three dashes... this will error out

2024-07-23 14:51 UTC, guneriu commented on yilu-common/values-test.yaml
> +secrets:
nice catch @davidmukiibi-yilu I'll adjust it, I was also debating if I can use  but for now it's enough https://developer.hashicorp.com/vault/docs/platform/k8s/vso/api-reference#vaultstaticsecretlist

2024-07-24 08:12 UTC, mayank-aggarwal-yilu submitted a review, later dismissed
lgtm

2024-07-24 11:57 UTC, guneriu commented on yilu-common/templates/_helpers.tpl
> +
example outputs from tests with not valid parameters

```
helm.go:84: [debug] execution error at (yilu-common/templates/notes.txt:1:4):
VALUES VALIDATION:
common: secrets.staticSecrets
    `secretKeys` and `transformation` can't be used together
```


```
helm.go:84: [debug] execution error at (yilu-common/templates/notes.txt:1:4):
VALUES VALIDATION:
common: secrets.dynamicSecrets.aws
    `dynamicSecrets` with `aws` type and `aws` block can't be used together
```

2024-07-24 13:56 UTC, davidmukiibi-yilu commented
do we still need the aws block?

2024-07-25 10:01 UTC, davidmukiibi-yilu approved these changes

2024-07-25 10:04 UTC, guneriu commented on yilu-common/values-test.yaml
> +  dynamicSecrets:
based on the test values, template rendering results to this.

```
---
# Source: yilu-common/templates/vaultSecret.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: hede
  labels:
    simpletrip: demo-service
spec:
  namespace: admin/yiluhub/
  vaultAuthRef: vault-secrets-operator/default
  mount: aws/secret-engine
  path:
  renewalPercent: 70
  destination:
    name: hede
    create: true
  rolloutRestartTargets:
    - kind: Deployment
      name: demo-service
---
# Source: yilu-common/templates/vaultSecret.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: booking-secrets
  labels:
    simpletrip: demo-service
spec:
  namespace: admin/yiluhub/
  vaultAuthRef: vault-secrets-operator/default
  mount: kv/services/secrets
  type: kv-v2
  path: bookings
  version: 1
  refreshAfter: 1h
  destination:
    name: booking-secrets
    create: true
---
# Source: yilu-common/templates/vaultSecret.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: payment-secrets
  labels:
    simpletrip: demo-service
spec:
  namespace: admin/yiluhub/
  vaultAuthRef: vault-secrets-operator/default
  mount: kv/services/secrets
  type: kv-v2
  path: payments
  version: 1
  refreshAfter: 1h
  destination:
    name: payment-secrets
    create: true
    transformation:
      templates:
        application.yaml:
          text: |
            {{- printf "%s" (b64dec (get .Secrets "application.yaml")) -}}
 ```

2024-07-25 10:06 UTC, guneriu commented
> do we still need the aws block?

this will be tackled later after going through the services, if we see we don't need the feature, then we can remove this.
but I feel it can be useful, let's see.

2024-07-25 10:18 UTC, merged